# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mlsom <- function(data, parameters, dtype, niter, nhbrdist, alphas, radii) {
    .Call(`_smlsom_mlsom`, data, parameters, dtype, niter, nhbrdist, alphas, radii)
}

mlsom_clf <- function(X, y, nsubc, cumnsubc, parameters, dtype, niter, nhbrdist, alphas, radii) {
    .Call(`_smlsom_mlsom_clf`, X, y, nsubc, cumnsubc, parameters, dtype, niter, nhbrdist, alphas, radii)
}

onebatch <- function(data, parameters, classes, dtype) {
    .Call(`_smlsom_onebatch`, data, parameters, classes, dtype)
}

classifsubc_within_class <- function(X, y, nsubc, cumnsubc, parameters, dtype) {
    .Call(`_smlsom_classifsubc_within_class`, X, y, nsubc, cumnsubc, parameters, dtype)
}

loglikelihood <- function(data, parameters, llconst, dtype) {
    .Call(`_smlsom_loglikelihood`, data, parameters, llconst, dtype)
}

classification_loglikelihood <- function(data, parameters, classes, llconst, dtype) {
    .Call(`_smlsom_classification_loglikelihood`, data, parameters, classes, llconst, dtype)
}

loglikelihood_const <- function(data, dtype) {
    .Call(`_smlsom_loglikelihood_const`, data, dtype)
}

eval_without <- function(target_m, data, search_mrange, parameters, classes, llconst, dtype) {
    .Call(`_smlsom_eval_without`, target_m, data, search_mrange, parameters, classes, llconst, dtype)
}

model_test1 <- function(A) {
    .Call(`_smlsom_model_test1`, A)
}

model_test2 <- function(x, mu, Sigma) {
    .Call(`_smlsom_model_test2`, x, mu, Sigma)
}

model_test3 <- function(x, mu1, Sigma1, mu2, Sigma2) {
    .Call(`_smlsom_model_test3`, x, mu1, Sigma1, mu2, Sigma2)
}

model_test4 <- function(alpha, x, mu, Sigma) {
    .Call(`_smlsom_model_test4`, alpha, x, mu, Sigma)
}

model_io_test1 <- function(parameters) {
    invisible(.Call(`_smlsom_model_io_test1`, parameters))
}

model_io_test2 <- function(parameters) {
    invisible(.Call(`_smlsom_model_io_test2`, parameters))
}

model_io_test3 <- function(parameters, dtype) {
    .Call(`_smlsom_model_io_test3`, parameters, dtype)
}

model_io_test4 <- function(parameters, p) {
    .Call(`_smlsom_model_io_test4`, parameters, p)
}

clustering_test1 <- function(data, parameters) {
    .Call(`_smlsom_clustering_test1`, data, parameters)
}

clustering_test2 <- function(t, niter, radii) {
    .Call(`_smlsom_clustering_test2`, t, niter, radii)
}

clustering_test3 <- function(t, niter, alphas) {
    .Call(`_smlsom_clustering_test3`, t, niter, alphas)
}

list_test <- function(X, classes, M) {
    invisible(.Call(`_smlsom_list_test`, X, classes, M))
}

method_test1 <- function(parameters, target_m, p) {
    .Call(`_smlsom_method_test1`, parameters, target_m, p)
}

method_test2 <- function(data, parameters, classes, target_m) {
    .Call(`_smlsom_method_test2`, data, parameters, classes, target_m)
}

method_test3 <- function(data, parameters, classes) {
    .Call(`_smlsom_method_test3`, data, parameters, classes)
}

